routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth'], function () {
    //    Route::get('/link1', function ()    {
//        // Uses Auth Middleware
//    });

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
    Route::resource('tipounidadesmedida', 'TipoUnidadesMedidaController');
    Route::get('tipounidadesmedida/{id}/destroy',[
    	'uses' => 'TipoUnidadesMedidaController@destroy',
    	'as' => 'tipounidadesmedida.destroy'
    ]);
    Route::resource('unidadesmedida', 'UnidadesMedidaController');
    Route::get('unidadesmedida/{id}/destroy',[
    	'uses' => 'UnidadesMedidaController@destroy',
    	'as' => 'unidadesmedida.destroy'
    ]);
    Route::resource('variables', 'VariablesController');
    Route::get('variables/{id}/destroy',[
    	'uses' => 'VariablesController@destroy',
    	'as' => 'variables.destroy'
    ]);

    Route::get('dropdown', function(Request $request){
   
    $id = $request->input('option');  
    $unidades = DB::table('unidades_medida')->where('tipo_unidad_medida_fk',$id )->get();
    if($unidades->all()){
         $retorno=$unidades->pluck('nombre', 'id');
    } 
    else{
         $retorno=[''=>'No tiene unidades agregadas'];       
   }  
    return $retorno;
    });

    Route::post('mediciones',[
        'uses' => 'MedicionesController@store',
        'as' => 'mediciones.store'
    ]);
    Route::get('listado_graficas',[
    	'uses' => 'GraficasController@index',
    	'as' => 'listado_graficas.index'
    ]);   
    Route::get('grafica_registros/{anio}/{mes}', 'GraficasController@registros_mes');
    Route::get('grafica_publicaciones', 'GraficasController@total_publicaciones');
    Route::get('tokens', function () {
    return view('admin.tokens.tokens');
    });
     Route::get('live_grafica/{id}',[
        'uses' => 'HomeController@livegrafica',
        'as' => 'live_grafica.livegrafica'
    ]);  
});

app/Http/Controllers/TipoUnidadesMedidaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\TipoUnidadMedida;
use Laracasts\Flash\FlashServiceProvider;

class TipoUnidadesMedidaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tipounidades = TipoUnidadMedida::orderBy('id','DESC')->paginate(5);
        return view('admin.tipounidadesmedida.tipounidadesmedida')->with('tipounidades', $tipounidades);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tipounidadesmedida.tipounidadesmedida');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $tipounidad= new TipoUnidadMedida($request->all());
        $request->validate([
        'nombre' => 'required|unique:tipo_unidades_medida,nombre|max:255|alpha_spaces',        
        ]);
        $tipounidad->save();
        flash('Se ha insertado '.$tipounidad->nombre.' de forma exitosa!')->success()->important();
        return redirect()->route('tipounidadesmedida.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $records = TipoUnidadMedida::find($id);        
        $tipounidades = TipoUnidadMedida::orderBy('id','DESC')->paginate(5);
        return view('admin.tipounidadesmedida.tipounidadesmedida')->with(['records'=> $records,'tipounidades'=> $tipounidades]);      
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $tipounidad = TipoUnidadMedida::find($id);
      $tipounidad->fill($request->all());     
      $tipounidad->save();
      flash('Se ha editado '.$tipounidad->nombre.' de forma exitosa!')->success()->important();
      return redirect()->route('tipounidadesmedida.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $tipounidad = TipoUnidadMedida::find($id);      
       $tipounidad->delete();
       flash('Se ha eliminado '.$tipounidad->nombre.' de forma exitosa!')->warning()->important();
       return redirect()->route('tipounidadesmedida.index');
    }
}

resources/views/admin/tipounidadesmedida/crear.blade.php
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Agregar tipo de unidad de medida</h3>
        <div class="box-tools pull-right">
          <!-- Buttons, labels, and many other things can be placed here! -->
          <!-- Here is a label for example -->
         
        </div>
    <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    {!! Form::open(['route'=>'tipounidadesmedida.store', 'method'=>'POST', 'data-toggle'=>'validator', 'role'=>'form']) !!}
        <div class="box-body"> 
            <div class="form-group">
              {!! Form::label('nombre','Nombre',['class'=>'label label-default']) !!}
              {!! Form::text('nombre',null , ['class'=>'form-control','placeholder'=>'Ingrese el nombre','required']) !!}                               
            </div>                       
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            {!! Form::submit('Agregar' ,['class'=>'btn btn-primary']) !!} 
        </div>
        <!-- box-footer -->
    {!! Form::close() !!}
</div>
<!-- /.box -->

resources/views/admin/tipounidadesmedida/editar.blade.php
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Editar tipo de unidad de medida: {{ $records->nombre }}</h3>
        <div class="box-tools pull-right">
          <!-- Buttons, labels, and many other things can be placed here! -->
          <!-- Here is a label for example -->
         
        </div>
    <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    {!! Form::open(['route'=> ['tipounidadesmedida.update',$records], 'method'=>'PUT']) !!}
        <div class="box-body"> 
            <div class="form-group">
              {!! Form::label('nombre','Nombre',['class'=>'label label-default']) !!}
              {!! Form::text('nombre',$records->nombre, ['class'=>'form-control','placeholder'=>'Ingrese el nombre','required']) !!}                               
            </div>                       
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            {!! Form::submit('Editar' ,['class'=>'btn btn-primary']) !!} 
        </div>
        <!-- box-footer -->
    {!! Form::close() !!}
</div>
<!-- /.box -->

resources/views/admin/tipounidadesmedida/listado.blade.php
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Listado de registros creados</h3>
        <div class="box-tools pull-right">
          <!-- Buttons, labels, and many other things can be placed here! -->
          <!-- Here is a label for example -->
         
        </div>
    <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    
        <div class="box-body"> 
         	<table class="table table-hover">
				<thead>
					<th>Id</th>
					<th>Nombre</th>
					<th>Acciones</th>
				</thead>
				<tbody>					
					@foreach($tipounidades as $tipounidad)
						<tr>
							<td>{{ $tipounidad->id}}</td>
							<td>{{ $tipounidad->nombre}}</td>
							<td>
                                <a href="{{ route('tipounidadesmedida.edit', $tipounidad->id) }}" data-toggle="tooltip" title="Editar Registro" class="btn btn-warning "><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                                <a href="{{ route('tipounidadesmedida.destroy', $tipounidad->id) }}" data-toggle="tooltip" title="Eliminar Registro" class="btn btn-danger "><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                            </td>
						</tr>
					@endforeach
				</tbody>
			</table>			                    
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
        	{{ $tipounidades->links() }}    
        </div>
        <!-- box-footer -->    
</div>
<!-- /.box -->

resources/views/admin/tipounidadesmedida/tipounidadesmedida.blade.php
@extends('adminlte::page')

@section('htmlheader_title')
Administración de tipos de unidades de medida	
@endsection
@section('contentheader_title')
   Tipos de unidades de medida
@endsection
@section('contentheader_description')
    
@endsection
@section('main-content')
	<div class="container-fluid spark-screen">
		<div class="row">
			<div class="col-md-9 col-md-offset-1">

                @isset($records)
                    @include('admin.tipounidadesmedida.editar')
                @endisset
                @empty($records)
                    @include('admin.tipounidadesmedida.crear')
                @endempty              
                @include('admin.tipounidadesmedida.listado')
			</div>
		</div>
	</div>
@endsection