routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth'], function () {
    //    Route::get('/link1', function ()    {
//        // Uses Auth Middleware
//    });

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
    Route::resource('tipounidadesmedida', 'TipoUnidadesMedidaController');
    Route::get('tipounidadesmedida/{id}/destroy',[
    	'uses' => 'TipoUnidadesMedidaController@destroy',
    	'as' => 'tipounidadesmedida.destroy'
    ]);
    Route::resource('unidadesmedida', 'UnidadesMedidaController');
    Route::get('unidadesmedida/{id}/destroy',[
    	'uses' => 'UnidadesMedidaController@destroy',
    	'as' => 'unidadesmedida.destroy'
    ]);
    Route::resource('variables', 'VariablesController');
    Route::get('variables/{id}/destroy',[
    	'uses' => 'VariablesController@destroy',
    	'as' => 'variables.destroy'
    ]);

    Route::get('dropdown', function(Request $request){
   
    $id = $request->input('option');  
    $unidades = DB::table('unidades_medida')->where('tipo_unidad_medida_fk',$id )->get();
    if($unidades->all()){
         $retorno=$unidades->pluck('nombre', 'id');
    } 
    else{
         $retorno=[''=>'No tiene unidades agregadas'];       
   }  
    return $retorno;
    });

    Route::post('mediciones',[
        'uses' => 'MedicionesController@store',
        'as' => 'mediciones.store'
    ]);
    Route::get('listado_graficas',[
    	'uses' => 'GraficasController@index',
    	'as' => 'listado_graficas.index'
    ]);   
    Route::get('grafica_registros/{anio}/{mes}', 'GraficasController@registros_mes');
    Route::get('grafica_publicaciones', 'GraficasController@total_publicaciones');
    Route::get('tokens', function () {
    return view('admin.tokens.tokens');
    });
     Route::get('live_grafica/{id}',[
        'uses' => 'HomeController@livegrafica',
        'as' => 'live_grafica.livegrafica'
    ]);  
});

app/Variable.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Variable extends Model
{
	protected $table = "variables";

	protected $fillable = ['nombre','unidad_medida_fk'];

	public function mediciones(){

		return $this->hasMany("App\Medicion");		
	}
	public function unidad_medida(){

		return $this->belongsTo('App\UnidadMedida', 'unidad_medida_fk');  		
	}
}

app/Http/Controllers/VariablesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\TipoUnidadMedida;
use App\UnidadMedida;
use App\Variable;
use Illuminate\Support\Facades\DB;
class VariablesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()    
    {
        $variables= Variable::orderBy('nombre','DESC')->paginate(5);
        $tipos = TipoUnidadMedida::orderBy('nombre','Desc')->pluck('nombre', 'id');                
        return view('admin.variables.variables')->with(['tipos'=> $tipos,'variables'=>$variables]); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('admin.variables.variables');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $variable= new Variable($request->all());
        $variable->unidad_medida_fk = $request->unidad_medida_fk;      
        $variable->save();
        flash('Se ha insertado '.$variable->nombre.' de forma exitosa!')->success()->important();
        return redirect()->route('variables.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $records = Variable::find($id);
        $records->each(function($records){
            $records->unidad_medida;
        });
         
        $unidades = UnidadMedida::find( $records->unidad_medida->id);
        $unidades->each(function($unidades){
            $unidades->tipo_unidad_medida;
        });
        $unidadesr = DB::table('unidades_medida')->where('tipo_unidad_medida_fk',$unidades->tipo_unidad_medida_fk )->get();
        $retorno=$unidadesr->pluck('nombre', 'id');                            
        $variables= Variable::orderBy('nombre','DESC')->paginate(5);      
        $tipos = TipoUnidadMedida::orderBy('nombre','DESC')->pluck('nombre', 'id');       
        return view('admin.variables.variables')->with(['records'=> $records,'tipos'=> $tipos, 'variables'=>$variables,'unidades'=>$unidades,'retorno'=>$retorno]); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $variable = Variable::find($id);        
        $variable->fill($request->all());     
        $variable->save();
        flash('Se ha editado '.$variable->nombre.' de forma exitosa!')->success()->important();
        return redirect()->route('variables.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $variable = Variable::find($id);      
        $variable->delete();
        flash('Se ha eliminado '.$variable->nombre.' de forma exitosa!')->warning()->important();
        return redirect()->route('variables.index');
    }
}

resources/views/admin/variables/crear.blade.php
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Agregar Variable</h3>
        <div class="box-tools pull-right">
          <!-- Buttons, labels, and many other things can be placed here! -->
          <!-- Here is a label for example -->
         
        </div>
    <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    {!! Form::open(['route'=>'variables.store', 'method'=>'POST', 'data-toggle'=>'validator', 'role'=>'form']) !!}
        <div class="box-body"> 
            <div class="form-group">
              {!! Form::label('nombre','Nombre',['class'=>'label label-default']) !!}
              {!! Form::text('nombre',null , ['class'=>'form-control','placeholder'=>'Ingrese el nombre','required']) !!}                               
            </div>
             <div class="form-group">
              {!! Form::label('tipos','Tipos de unidad',['class'=>'label label-default']) !!}
              {!! Form::select('tipos',$tipos,null,['class'=>'form-control','placeholder'=>'Seleccione un tipo de  unidad de medida']) !!}                        
            </div>
             <div class="form-group">           
              {!! Form::label('unidad_medida_fk','Unidad de medida',['class'=>'label label-default']) !!}
              {!! Form::select('unidad_medida_fk',['' => 'Seleccione una una opción'],null,['class'=>'form-control','required']) !!}                               
            </div>                                
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            {!! Form::submit('Agregar' ,['class'=>'btn btn-primary']) !!} 
        </div>
        <!-- box-footer -->
    {!! Form::close() !!}
</div>
<!-- /.box -->

resources/views/admin/variables/editar.blade.php
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Editar Variable</h3>
        <div class="box-tools pull-right">
          <!-- Buttons, labels, and many other things can be placed here! -->
          <!-- Here is a label for example -->
         
        </div>
    <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    {!! Form::open(['route'=>['variables.update',$records], 'method'=>'PUT', 'data-toggle'=>'validator', 'role'=>'form']) !!}
        <div class="box-body"> 
            <div class="form-group">
              {!! Form::label('nombre','Nombre',['class'=>'label label-default']) !!}
              {!! Form::text('nombre',$records->nombre , ['class'=>'form-control','placeholder'=>'Ingrese el nombre','required']) !!}                               
            </div>
             <div class="form-group">
              {!! Form::label('tipos','Tipos de unidad',['class'=>'label label-default']) !!}
              {!! Form::select('tipos',$tipos,$unidades->tipo_unidad_medida_fk,['class'=>'form-control','placeholder'=>'Seleccione un tipo de unidad de medida']) !!}                        
            </div>
             <div class="form-group">           
              {!! Form::label('unidad_medida_fk','Unidad de medida',['class'=>'label label-default']) !!}
              {!! Form::select('unidad_medida_fk',$retorno,$records->unidad_medida_fk,['class'=>'form-control','placeholder'=>'Seleccione un tipo de unidad de medida']) !!}                             
            </div>                                
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            {!! Form::submit('Editar' ,['class'=>'btn btn-primary']) !!} 
        </div>
        <!-- box-footer -->
    {!! Form::close() !!}
</div>
<!-- /.box -->

resources/views/admin/variables/listado.blade.php
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Listado de registros creados</h3>
        <div class="box-tools pull-right">
          <!-- Buttons, labels, and many other things can be placed here! -->
          <!-- Here is a label for example -->
         
        </div>
    <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    
        <div class="box-body"> 
         	<table class="table table-hover">
				<thead>
					<th>Id</th>
					<th>Nombre</th>
					<th>Unidad de medida</th>                    
                    <th>Acciones</th>
				</thead>
				<tbody>					
					@foreach($variables as $variable)
						<tr>
							<td>{{ $variable->id}}</td>
							<td>{{ $variable->nombre}}</td>
                            <td>{{ $variable->unidad_medida->nombre}}</td>                           
							<td>
                                <a href="{{ route('variables.edit', $variable->id) }}" data-toggle="tooltip" title="Editar Registro" class="btn btn-warning "><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                                <a href="{{ route('variables.destroy', $variable->id) }}" data-toggle="tooltip" title="Eliminar Registro" class="btn btn-danger "><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                            </td>
						</tr>
					@endforeach
				</tbody>
			</table>			                    
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
        	{{ $variables->links() }}    
        </div>
        <!-- box-footer -->    
</div>
<!-- /.box -->

resources/views/admin/variables/scripts.blade.php
<script type="text/javascript" language="javascript" class="init">
	window.onload = function() {			
		$('#tipos').change(function(){
			$.get("{{ url('dropdown')}}",
			{ option: $(this).val() },
			function(data) {
				$('#unidad_medida_fk').empty();
				$.each(data, function(key, element) {
					$('#unidad_medida_fk').append("<option value='" + key + "'>" + element + "</option>");
				});
			});
		});
	};
		
</script>

resources/views/admin/variables/variables.blade.php
@extends('adminlte::page')

@section('htmlheader_title')
	Administración de variables
@endsection
@section('contentheader_title')
   Variables
@endsection
@section('contentheader_description')
    
@endsection
@section('main-content')
	<div class="container-fluid spark-screen">
		<div class="row">
			<div class="col-md-9 col-md-offset-1">

                @isset($records)
                    @include('admin.variables.editar')
                @endisset
                @empty($records)
                    @include('admin.variables.crear')
                @endempty              
                @include('admin.variables.listado')
                @include('admin.variables.scripts')
			</div>
		</div>
	</div>

@endsection