routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth'], function () {
    //    Route::get('/link1', function ()    {
//        // Uses Auth Middleware
//    });

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
    Route::resource('tipounidadesmedida', 'TipoUnidadesMedidaController');
    Route::get('tipounidadesmedida/{id}/destroy',[
    	'uses' => 'TipoUnidadesMedidaController@destroy',
    	'as' => 'tipounidadesmedida.destroy'
    ]);
    Route::resource('unidadesmedida', 'UnidadesMedidaController');
    Route::get('unidadesmedida/{id}/destroy',[
    	'uses' => 'UnidadesMedidaController@destroy',
    	'as' => 'unidadesmedida.destroy'
    ]);
    Route::resource('variables', 'VariablesController');
    Route::get('variables/{id}/destroy',[
    	'uses' => 'VariablesController@destroy',
    	'as' => 'variables.destroy'
    ]);

    Route::get('dropdown', function(Request $request){
   
    $id = $request->input('option');  
    $unidades = DB::table('unidades_medida')->where('tipo_unidad_medida_fk',$id )->get();
    if($unidades->all()){
         $retorno=$unidades->pluck('nombre', 'id');
    } 
    else{
         $retorno=[''=>'No tiene unidades agregadas'];       
   }  
    return $retorno;
    });

    Route::post('mediciones',[
        'uses' => 'MedicionesController@store',
        'as' => 'mediciones.store'
    ]);
    Route::get('listado_graficas',[
    	'uses' => 'GraficasController@index',
    	'as' => 'listado_graficas.index'
    ]);   
    Route::get('grafica_registros/{anio}/{mes}', 'GraficasController@registros_mes');
    Route::get('grafica_publicaciones', 'GraficasController@total_publicaciones');
    Route::get('tokens', function () {
    return view('admin.tokens.tokens');
    });
     Route::get('live_grafica/{id}',[
        'uses' => 'HomeController@livegrafica',
        'as' => 'live_grafica.livegrafica'
    ]);  
});

app/Http/Controllers/UnidadesMedidaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\TipoUnidadMedida;
use App\UnidadMedida;
use Laracasts\Flash\FlashServiceProvider;

class UnidadesMedidaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tipos = TipoUnidadMedida::orderBy('nombre','Desc')->pluck('nombre', 'id');
        $unidades=UnidadMedida::orderBy('id','Desc')->paginate(5);
        $unidades->each(function($unidades){
        $unidades->tipo_unidad_medida;
        });             
        return view('admin.unidadesmedida.unidadesmedida')->with(['tipos'=> $tipos,'unidades'=> $unidades]); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.unidadesmedida.unidadesmedida');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $unidad= new UnidadMedida($request->all());
        $unidad->tipo_unidad_medida_fk = $request->tipo_unidad_medida_fk;      
        $unidad->save();
        flash('Se ha insertado '.$unidad->nombre.' de forma exitosa!')->success()->important();
        return redirect()->route('unidadesmedida.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $records = UnidadMedida::find($id);
        $records->each(function($records){
            $records->tipo_unidad_medida;
        });
        if($records->principal=='SI')
        {
            $records->principal=true;
        }
        else{
             $records->principal=false;
        }       
        $unidades = UnidadMedida::orderBy('id','DESC')->paginate(5);
        $unidades->each(function($unidades){
            $unidades->tipo_unidad_medida;
        });  
        $tipos = TipoUnidadMedida::orderBy('nombre','DESC')->pluck('nombre', 'id');       
        return view('admin.unidadesmedida.unidadesmedida')->with(['records'=> $records,'unidades'=> $unidades,'tipos'=> $tipos]); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    
      $unidad = UnidadMedida::find($id);
      if ($request->principal==null){$request->principal='NO';}
      $unidad->principal=$request->principal;
      $unidad->fill($request->all());     
      $unidad->save();
      flash('Se ha editado '.$unidad->nombre.' de forma exitosa!')->success()->important();
      return redirect()->route('unidadesmedida.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $unidad = UnidadMedida::find($id);      
        $unidad->delete();
        flash('Se ha eliminado '.$unidad->nombre.' de forma exitosa!')->warning()->important();
        return redirect()->route('unidadesmedida.index');
    }
}

resources/views/admin/unidadesmedida/crear.blade.php
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Agregar unidad de medida</h3>
        <div class="box-tools pull-right">
          <!-- Buttons, labels, and many other things can be placed here! -->
          <!-- Here is a label for example -->
         
        </div>
    <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    {!! Form::open(['route'=>'unidadesmedida.store', 'method'=>'POST', 'data-toggle'=>'validator', 'role'=>'form']) !!}
        <div class="box-body"> 
            <div class="form-group">
              {!! Form::label('nombre','Nombre',['class'=>'label label-default']) !!}
              {!! Form::text('nombre',null , ['class'=>'form-control','placeholder'=>'Ingrese el nombre','required']) !!}                               
            </div>
             <div class="form-group">           
              {!! Form::label('tipo_unidad_medida_fk','Tipo de unidad',['class'=>'label label-default']) !!}
              {!! Form::select('tipo_unidad_medida_fk',$tipos,null,['class'=>'form-control','placeholder'=>'Seleccione un tipo','required']) !!}                               
            </div>
             <div class="form-group">
              {!! Form::label('sigla','Sigla',['class'=>'label label-default']) !!}
              {!! Form::text('sigla',null , ['class'=>'form-control','placeholder'=>'Ingrese la sigla o abreviación','required','maxlength'=>'10']) !!}                               
            </div>
            <div class="form-group">
              {!! Form::label('tasa_conversion','Tasa de conversion',['class'=>'label label-default']) !!}
              {!! Form::number('tasa_conversion',null , ['class'=>'form-control','placeholder'=>'Ingrese la tasa de conversion','required','max'=>'99999','min'=>'0', 'data-bind'=>'value:replyNumber']) !!}                               
            </div>            
            <div class="checkbox">
                <label>
                    {!! Form::checkbox('principal', 'SI',false,['class'=>'form-check-input'])!!}
                    Principal 
                </label>               
            </div>           
                                 
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            {!! Form::submit('Agregar' ,['class'=>'btn btn-primary']) !!} 
        </div>
        <!-- box-footer -->
    {!! Form::close() !!}
</div>
<!-- /.box -->

resources/views/admin/unidadesmedida/editar.blade.php
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Editar unidad de medida: {{ $records->nombre }}</h3>
        <div class="box-tools pull-right">
          <!-- Buttons, labels, and many other things can be placed here! -->
          <!-- Here is a label for example -->
         
        </div>
    <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    {!! Form::open(['route'=> ['unidadesmedida.update',$records], 'method'=>'PUT']) !!}
        <div class="box-body"> 
            <div class="form-group">
              {!! Form::label('nombre','Nombre',['class'=>'label label-default']) !!}
              {!! Form::text('nombre',$records->nombre , ['class'=>'form-control','placeholder'=>'Ingrese el nombre','required']) !!}                               
            </div>
             <div class="form-group">           
              {!! Form::label('tipo_unidad_medida_fk','Tipo de unidad',['class'=>'label label-default']) !!}
              {!! Form::select('tipo_unidad_medida_fk',$tipos,$records->tipo_unidad_medida->id,['class'=>'form-control','placeholder'=>'Seleccione un tipo','required']) !!}                               
            </div>
             <div class="form-group">
              {!! Form::label('sigla','Sigla',['class'=>'label label-default']) !!}
              {!! Form::text('sigla',$records->sigla , ['class'=>'form-control','placeholder'=>'Ingrese la sigla o abreviación','required','maxlength'=>'10']) !!}                               
            </div>
            <div class="form-group">
              {!! Form::label('tasa_conversion','Tasa de conversion',['class'=>'label label-default']) !!}
              {!! Form::number('tasa_conversion',$records->tasa_conversion , ['class'=>'form-control','placeholder'=>'Ingrese la tasa de conversion','required','max'=>'99999','min'=>'0', 'data-bind'=>'value:replyNumber']) !!}                               
            </div>            
            <div class="checkbox">
                <label>
                    {!! Form::checkbox('principal', 'SI',$records->principal,['class'=>'form-check-input']) !!}
                    Principal 
                </label>               
            </div>           
                                 
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            {!! Form::submit('Editar' ,['class'=>'btn btn-primary']) !!} 
        </div>
        <!-- box-footer -->
    {!! Form::close() !!}
</div>
<!-- /.box -->

resources/views/admin/unidadesmedida/listado.blade.php
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Listado de registros creados</h3>
        <div class="box-tools pull-right">
          <!-- Buttons, labels, and many other things can be placed here! -->
          <!-- Here is a label for example -->
         
        </div>
    <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    
        <div class="box-body"> 
         	<table class="table table-hover">
				<thead>
					<th>Id</th>
					<th>Nombre</th>
					<th>Tipo de unidad</th>
                    <th>Sigla</th>
                    <th>Tasa de conversión</th>
                    <th>Principal</th>
                    <th>Acciones</th>
				</thead>
				<tbody>					
					@foreach($unidades as $unidad)
						<tr>
							<td>{{ $unidad->id}}</td>
							<td>{{ $unidad->nombre}}</td>
                            <td>{{ $unidad->tipo_unidad_medida->nombre}}</td>
                            <td>{{ $unidad->sigla}}</td>
                            <td>{{ $unidad->tasa_conversion}}</td>
                            <td>{{ $unidad->principal}}</td>
							<td>
                                <a href="{{ route('unidadesmedida.edit', $unidad->id) }}" data-toggle="tooltip" title="Editar Registro" class="btn btn-warning "><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                                <a href="{{ route('unidadesmedida.destroy', $unidad->id) }}" data-toggle="tooltip" title="Eliminar Registro" class="btn btn-danger "><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                            </td>
						</tr>
					@endforeach
				</tbody>
			</table>			                    
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
        	{{ $unidades->links() }}    
        </div>
        <!-- box-footer -->    
</div>
<!-- /.box -->

resources/views/admin/unidadesmedida/unidadesmedida.blade.php
@extends('adminlte::page')

@section('htmlheader_title')
Administración de unidades de medida
@endsection
@section('contentheader_title')
   Unidades de medida
@endsection
@section('contentheader_description')
    
@endsection
@section('main-content')
	<div class="container-fluid spark-screen">
		<div class="row">
			<div class="col-md-9 col-md-offset-1">

                @isset($records)
                    @include('admin.unidadesmedida.editar')
                @endisset
                @empty($records)
                    @include('admin.unidadesmedida.crear')
                @endempty              
                @include('admin.unidadesmedida.listado')
			</div>
		</div>
	</div>
@endsection